import { Property, User, Conversation, Message } from './types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Rajesh Kumar',
    phone: '+91 98765 43210',
    email: 'rajesh@email.com',
    role: 'owner',
    aadhaarVerified: true,
    createdAt: '2026-01-15',
  },
  {
    id: 'user-2',
    name: 'Priya Sharma',
    phone: '+91 87654 32109',
    role: 'owner',
    aadhaarVerified: true,
    createdAt: '2026-02-20',
  },
  {
    id: 'user-3',
    name: 'Amit Patel',
    phone: '+91 76543 21098',
    role: 'buyer',
    aadhaarVerified: false,
    createdAt: '2026-03-10',
  },
  {
    id: 'user-4',
    name: 'Admin',
    phone: '+91 99999 00000',
    role: 'admin',
    aadhaarVerified: true,
    createdAt: '2026-01-01',
  },
];

export const mockProperties: Property[] = [
  {
    id: 'prop-1',
    title: 'Spacious 2BHK in Lajpat Nagar',
    description: 'Bright and airy 2BHK apartment in the heart of Lajpat Nagar. Close to metro, market, and schools. Semi-furnished with modular kitchen.',
    propertyType: 'room',
    listingType: 'rent',
    price: 18000,
    priceUnit: 'month',
    size: 850,
    sizeUnit: 'sqft',
    roomConfig: '2BHK',
    furnishedStatus: 'semi-furnished',
    address: 'A-45, Lajpat Nagar II',
    locality: 'Lajpat Nagar',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110024',
    latitude: 28.5679,
    longitude: 77.2383,
    photos: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    amenities: ['Parking', 'Power Backup', 'Lift', 'Water Supply', 'Modular Kitchen', 'AC'],
    ownerId: 'user-1',
    ownerName: 'Rajesh Kumar',
    ownerPhone: '+91 98765 43210',
    verified: 'verified',
    status: 'active',
    featured: true,
    availableFrom: '2026-07-01',
    createdAt: '2026-05-10',
    updatedAt: '2026-06-01',
    views: 342,
    saves: 28,
  },
  {
    id: 'prop-2',
    title: 'Residential Plot in Dwarka Sector 19',
    description: 'Prime residential plot in Dwarka Sector 19. 200 sq yards, corner plot with road on two sides. Perfect for building your dream home.',
    propertyType: 'plot',
    listingType: 'sale',
    price: 12000000,
    priceUnit: 'total',
    size: 200,
    sizeUnit: 'sqyd',
    landType: 'residential',
    address: 'Plot No. 12, Sector 19',
    locality: 'Dwarka',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110075',
    latitude: 28.5921,
    longitude: 77.0460,
    photos: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800',
      'https://images.unsplash.com/photo-1628624747186-a941c476b7ef?w=800',
    ],
    amenities: ['Corner Plot', 'Road Access', 'Electricity', 'Water Connection'],
    ownerId: 'user-2',
    ownerName: 'Priya Sharma',
    ownerPhone: '+91 87654 32109',
    verified: 'verified',
    status: 'active',
    featured: false,
    availableFrom: '2026-06-15',
    createdAt: '2026-04-20',
    updatedAt: '2026-05-30',
    views: 189,
    saves: 15,
  },
  {
    id: 'prop-3',
    title: '1BHK near Saket Metro',
    description: 'Cozy 1BHK flat just 5 minutes walk from Saket metro station. Fully furnished with modern amenities. Ideal for working professionals.',
    propertyType: 'room',
    listingType: 'rent',
    price: 12000,
    priceUnit: 'month',
    size: 450,
    sizeUnit: 'sqft',
    roomConfig: '1BHK',
    furnishedStatus: 'furnished',
    address: 'B-12, Pushp Vihar',
    locality: 'Saket',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110017',
    latitude: 28.5244,
    longitude: 77.2066,
    photos: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800',
    ],
    amenities: ['Furnished', 'AC', 'WiFi', 'Power Backup', 'Water Supply'],
    ownerId: 'user-1',
    ownerName: 'Rajesh Kumar',
    ownerPhone: '+91 98765 43210',
    verified: 'verified',
    status: 'active',
    featured: false,
    availableFrom: '2026-06-20',
    createdAt: '2026-05-25',
    updatedAt: '2026-06-05',
    views: 567,
    saves: 42,
  },
  {
    id: 'prop-4',
    title: 'Commercial Land on NH-48',
    description: 'Strategic commercial land on NH-48 near Gurugram border. 500 sq yards, excellent for showroom, warehouse, or commercial complex.',
    propertyType: 'land',
    listingType: 'sale',
    price: 25000000,
    priceUnit: 'total',
    size: 500,
    sizeUnit: 'sqyd',
    landType: 'commercial',
    address: 'NH-48, Sector 24',
    locality: 'Gurugram',
    city: 'Gurugram',
    state: 'Haryana',
    pincode: '122002',
    latitude: 28.4595,
    longitude: 77.0266,
    photos: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800',
    ],
    amenities: ['Highway Facing', 'Electricity', 'Water', 'Fencing'],
    ownerId: 'user-2',
    ownerName: 'Priya Sharma',
    ownerPhone: '+91 87654 32109',
    verified: 'verified',
    status: 'active',
    featured: true,
    availableFrom: '2026-06-01',
    createdAt: '2026-03-15',
    updatedAt: '2026-05-20',
    views: 892,
    saves: 67,
  },
  {
    id: 'prop-5',
    title: '3BHK Luxury Flat in Defence Colony',
    description: 'Premium 3BHK in Defence Colony. Full floor, 1800 sqft, premium fittings, servant quarter, and 2 covered parking. Society gym and pool.',
    propertyType: 'room',
    listingType: 'rent',
    price: 45000,
    priceUnit: 'month',
    size: 1800,
    sizeUnit: 'sqft',
    roomConfig: '3BHK',
    furnishedStatus: 'furnished',
    address: 'E-Block, Defence Colony',
    locality: 'Defence Colony',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110024',
    latitude: 28.5733,
    longitude: 77.2345,
    photos: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    ],
    amenities: ['Swimming Pool', 'Gym', 'Club House', '24/7 Security', 'Covered Parking', 'Servant Quarter', 'Modular Kitchen', 'AC'],
    ownerId: 'user-2',
    ownerName: 'Priya Sharma',
    ownerPhone: '+91 87654 32109',
    verified: 'verified',
    status: 'active',
    featured: true,
    availableFrom: '2026-07-15',
    createdAt: '2026-05-01',
    updatedAt: '2026-06-08',
    views: 1024,
    saves: 89,
  },
  {
    id: 'prop-6',
    title: 'PG Accommodation in Karol Bagh',
    description: 'Shared PG room in Karol Bagh. Meals included, WiFi, cleaning service. Walking distance to metro. Great for students and freshers.',
    propertyType: 'room',
    listingType: 'rent',
    price: 8000,
    priceUnit: 'month',
    size: 120,
    sizeUnit: 'sqft',
    roomConfig: 'PG',
    furnishedStatus: 'furnished',
    address: '23, Ajmal Khan Road',
    locality: 'Karol Bagh',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110005',
    latitude: 28.6519,
    longitude: 77.1898,
    photos: [
      'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800',
    ],
    amenities: ['Meals Included', 'WiFi', 'Cleaning', 'Laundry', 'Power Backup'],
    ownerId: 'user-1',
    ownerName: 'Rajesh Kumar',
    ownerPhone: '+91 98765 43210',
    verified: 'verified',
    status: 'active',
    featured: false,
    availableFrom: '2026-06-10',
    createdAt: '2026-05-20',
    updatedAt: '2026-06-05',
    views: 445,
    saves: 31,
  },
  {
    id: 'prop-7',
    title: 'Agricultural Land in Faridabad',
    description: '10 bigha agricultural land in Faridabad. Fertile land with tube well and canal irrigation. Ideal for farming or long-term investment.',
    propertyType: 'land',
    listingType: 'sale',
    price: 8000000,
    priceUnit: 'total',
    size: 10,
    sizeUnit: 'bigha',
    landType: 'agricultural',
    address: 'Village Chandpur, Faridabad',
    locality: 'Faridabad',
    city: 'Faridabad',
    state: 'Haryana',
    pincode: '121004',
    latitude: 28.4089,
    longitude: 77.3178,
    photos: [
      'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800',
    ],
    amenities: ['Tube Well', 'Canal Irrigation', 'Road Access', 'Fertile Soil'],
    ownerId: 'user-2',
    ownerName: 'Priya Sharma',
    ownerPhone: '+91 87654 32109',
    verified: 'pending',
    status: 'active',
    featured: false,
    availableFrom: '2026-06-01',
    createdAt: '2026-04-10',
    updatedAt: '2026-05-15',
    views: 156,
    saves: 12,
  },
  {
    id: 'prop-8',
    title: 'Studio Apartment in Hauz Khas',
    description: 'Trendy studio apartment in Hauz Khas Village. Perfect for young professionals. Walking distance to parks, cafes, and metro.',
    propertyType: 'room',
    listingType: 'rent',
    price: 15000,
    priceUnit: 'month',
    size: 350,
    sizeUnit: 'sqft',
    roomConfig: 'studio',
    furnishedStatus: 'furnished',
    address: 'F-8, Hauz Khas Village',
    locality: 'Hauz Khas',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110016',
    latitude: 28.5494,
    longitude: 77.2001,
    photos: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    amenities: ['Fully Furnished', 'WiFi', 'AC', 'Geyser', 'Modular Kitchen'],
    ownerId: 'user-1',
    ownerName: 'Rajesh Kumar',
    ownerPhone: '+91 98765 43210',
    verified: 'verified',
    status: 'active',
    featured: false,
    availableFrom: '2026-06-25',
    createdAt: '2026-05-30',
    updatedAt: '2026-06-08',
    views: 678,
    saves: 53,
  },
];

export const mockConversations: Conversation[] = [
  {
    id: 'conv-1',
    propertyId: 'prop-1',
    propertyTitle: 'Spacious 2BHK in Lajpat Nagar',
    buyerId: 'user-3',
    buyerName: 'Amit Patel',
    ownerId: 'user-1',
    ownerName: 'Rajesh Kumar',
    lastMessage: 'Can I visit the flat this Saturday?',
    lastMessageTime: '2026-06-10T14:30:00',
    unreadCount: 2,
  },
  {
    id: 'conv-2',
    propertyId: 'prop-3',
    propertyTitle: '1BHK near Saket Metro',
    buyerId: 'user-3',
    buyerName: 'Amit Patel',
    ownerId: 'user-1',
    ownerName: 'Rajesh Kumar',
    lastMessage: 'Yes, the rent is negotiable for long-term stay.',
    lastMessageTime: '2026-06-09T18:45:00',
    unreadCount: 0,
  },
];

export const mockMessages: Record<string, Message[]> = {
  'conv-1': [
    {
      id: 'msg-1',
      conversationId: 'conv-1',
      senderId: 'user-3',
      senderName: 'Amit Patel',
      text: 'Hi, is this 2BHK still available?',
      timestamp: '2026-06-10T10:00:00',
      read: true,
    },
    {
      id: 'msg-2',
      conversationId: 'conv-1',
      senderId: 'user-1',
      senderName: 'Rajesh Kumar',
      text: 'Yes, it is available! Would you like to visit?',
      timestamp: '2026-06-10T10:15:00',
      read: true,
    },
    {
      id: 'msg-3',
      conversationId: 'conv-1',
      senderId: 'user-3',
      senderName: 'Amit Patel',
      text: 'Can I visit the flat this Saturday?',
      timestamp: '2026-06-10T14:30:00',
      read: false,
    },
  ],
};

export const amenitiesList: string[] = [
  'AC', 'WiFi', 'Parking', 'Power Backup', 'Lift', 'Water Supply',
  'Swimming Pool', 'Gym', 'Club House', '24/7 Security', 'Covered Parking',
  'Modular Kitchen', 'Furnished', 'Servant Quarter', 'Garden', 'Play Area',
  'Housekeeping', 'Laundry', 'Meals Included', 'CCTV', 'Intercom',
  'Fire Safety', 'Rain Water Harvesting', 'Solar Panels', 'Visitor Parking',
];

export const indianStates: string[] = [
  'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh',
  'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand',
  'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur',
  'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab',
  'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura',
  'Uttar Pradesh', 'Uttarakhand', 'West Bengal', 'Delhi',
];

export const popularLocalities: string[] = [
  'Lajpat Nagar', 'Saket', 'Defence Colony', 'Hauz Khas', 'Karol Bagh',
  'Dwarka', 'Rohini', 'Vasant Kunj', 'Greater Kailash', 'Nehru Place',
  'Connaught Place', 'Chanakyapuri', 'Janakpuri', 'Uttam Nagar',
  'Dehradun', 'Gurugram', 'Noida', 'Faridabad', 'Ghaziabad',
];
